---
title: "Schedule"
---

Course Schedule

Note: Course schedule is subject to change without notice.

+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| **Day** | **Date**   | **Topic**                                                                                                                                                                                                                                          | **Due Today**                           |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
|         |            | [**First Day of Classes January 5**]{.underline}                                                                                                                                                                                                   |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| **1**   | 01/05/2026 | [*Lecture*]{.underline}: Basics of Workflow                                                                                                                                                                                                        |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Introduction to R & Workflow Basics; Quarto                                                                                                                                                                              |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       r4ds: Ch. [2](https://r4ds.hadley.nz/workflow-basics.html), [3](https://r4ds.hadley.nz/data-transform.html), [4](https://r4ds.hadley.nz/workflow-style), [6](https://r4ds.hadley.nz/workflow-scripts), [28](https://r4ds.hadley.nz/quarto) |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Zoom [link](https://ucdavis.zoom.us/rec/share/zEkihGYG_KwIRBk-zsU3TzqtB2tmYdu_NF2h6K7q8tbE8JHhlq_ZNkkt-AaIkAOq.UFz-nSnQn36-n9bm).                                                                                                                  |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| **2**   | 01/12/2026 | [*Lecture*]{.underline}: Reproducibility and Workflow Values                                                                                                                                                                                       |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Data Transformation: Introduction to **dplyr**                                                                                                                                                                           |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings:*]{.underline}                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       r4ds: Ch. [3](https://r4ds.hadley.nz/data-transform.html)                                                                                                                                                                                  |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Zoom [link](https://ucdavis.zoom.us/rec/share/0ZeuburMkGj1r0kJPwcEimodgKnr9BLtZrBPO0jRpEZwX2m5N0pFGKsoJGT6Qb7Z.ah6THzA60E1lVf6y).                                                                                                                  |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 3       | 01/19/2026 | NO CLASS - MLK DAY                                                                                                                                                                                                                                 | Problem Set 1 Due                       |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            |                                                                                                                                                                                                                                                    | (Grace period until 01/20/2026 at 2 PM) |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 4       | 01/26/2026 | [*Lecture*]{.underline}: Understanding and Assessing Data Quality                                                                                                                                                                                  |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Reshaping and Joining: Introduction to **tidyr**                                                                                                                                                                         |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       r4ds: Ch. [5](https://r4ds.hadley.nz/data-tidy)                                                                                                                                                                                            |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Zoom [link](https://ucdavis.zoom.us/rec/share/JTSfMVJHr4wKYCtPve1JPbqPjxqqKTJ10UmN3cTZ2UuXPMVxE_TqO9zI3x0VASUq.J3DMuQRBmi4Ndf8q).                                                                                                                  |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 5       | 02/02/2026 | [*Lecture*]{.underline}: Documenting Data and Procedures                                                                                                                                                                                           |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Using Codebooks to Aid Data Import                                                                                                                                                                                       |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       r4ds: Ch. [7](https://r4ds.hadley.nz/data-import), [20](https://r4ds.hadley.nz/spreadsheets), and [23](https://r4ds.hadley.nz/rectangling)                                                                                                 |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Zoom [link](https://ucdavis.zoom.us/rec/share/JAWulaFCO5dsZuAZ9TTLblZ_3ypkqnHN1zilzVhPHGLuupBCZ0cY051xfmy37UwL.l0BWA8y8buhimulb).                                                                                                                  |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 6       | 02/09/2026 | [*Lecture*]{.underline}: Functions                                                                                                                                                                                                                 | Problem Set 2 Due                       |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Iteration: Introduction to **purrr**                                                                                                                                                                                     |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       r4ds: Ch. [26](https://r4ds.hadley.nz/functions), [27](https://r4ds.hadley.nz/iteration)                                                                                                                                                   |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Zoom [link](https://ucdavis.zoom.us/rec/share/j0oyex6wfo5OlpFKC9fDe7PWn2a4eXtCwYfCxCbauac9sstJNeoDtrlT1mi_c-7z.Q03oOaLAO-EqvMd_).                                                                                                                  |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 7       | 02/16/2026 | NO CLASS                                                                                                                                                                                                                                           | **PROPOSALS DUE**                       |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | Review (PS 3) -- tidyverse: Using codebooks, functions, and iteration within a tidyverse framework (a series of in-class activities)                                                                                                               |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}: None                                                                                                                                                                                                                     |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 8       | 02/23/2026 | [*Lecture*]{.underline}: Data Structures in R                                                                                                                                                                                                      | Problem Set 3 Due                       |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Data Transformation: Dates, Strings, regex, and Other Tricky Classes                                                                                                                                                     |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -      r4ds: Ch. [12](https://r4ds.hadley.nz/logicals)-[18](https://r4ds.hadley.nz/missing-values)                                                                                                                                                 |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9       | 03/02/2026 | [*Lecture*]{.underline}: GitHub and Versioning                                                                                                                                                                                                     |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: (Functional) Tables & Figures                                                                                                                                                                                            |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       TBD                                                                                                                                                                                                                                        |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10      | 03/09/2026 | [*Lecture*]{.underline}: Using R resources efficiently                                                                                                                                                                                             | Problem Set 4 Due                       |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Workshop*]{.underline}: Parallelization: Introduction to **future** and **furrr**                                                                                                                                                                |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                          |                                         |
|         |            |                                                                                                                                                                                                                                                    |                                         |
|         |            | -       <https://dcgerard.github.io/advancedr/09_future.html>                                                                                                                                                                                      |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
|         | 03/16      | None                                                                                                                                                                                                                                               | Mini Problem Set 5 due                  |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
|         | 03/18/2026 | Final Project Due Date                                                                                                                                                                                                                             |                                         |
+---------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
